spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: "011102"
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info
    com.sxy: debug
  file:
    name: log/blog-dev.log